name: Main Entry Workflow

on:
  pull_request:
    types: [opened, synchronize, closed]
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - "bth/submit/*"
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "Branch: ${{ github.head_ref || github.ref_name }}"
          echo "Course ID: ${{ vars.COURSE_ID || 'python' }}"
          echo "Student ID: ${{ vars.STUDENT_CANVAS_ID || '52009' }}"
          
  kmom03-test:
    if: contains(github.head_ref, 'kmom03') || contains(github.ref, 'kmom03')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          pip install python-tester
          
      - name: Run kmom03 tests
        run: |
          echo "Running kmom03 tests..."
          python tests/kmom03/marvin2/test_1marvin2_structure.py
          python tests/kmom03/marvin2/test_3marvin2.py
          python tests/kmom03/marvin2/test_4main.py
          echo "All kmom03 tests passed!"
          
      - name: Submit to Canvas
        run: |
          echo "Assignment: kmom03"
          echo "Student ID: ${{ vars.STUDENT_CANVAS_ID || '52009' }}"
          echo "Course: ${{ vars.COURSE_ID || 'python' }}"
          echo "Status: PASS - All tests completed successfully"
          echo "Submission would be sent to Canvas (simulated)"
